let CONST = {};

CONST.CHECKOUT_KEY = "react-ez-checkout-token";
CONST.CART_KEY = "react-ez-cart-id";
CONST.ENABLED_SHOPS = [
    "saleor",
    "shopify"
];
CONST.COUNTRIES = {
    "AF": "Afghanistan",
    "EG": "Ägypten",
    "AX": "Åland",
    "AL": "Albanien",
    "DZ": "Algerien",
    "AS": "Amerikanisch-Samoa",
    "VI": "Amerikanische Jungferninseln",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarktis",
    "AG": "Antigua und Barbuda",
    "GQ": "Äquatorialguinea",
    "AR": "Argentinien",
    "AM": "Armenien",
    "AW": "Aruba",
    "AZ": "Aserbaidschan",
    "ET": "Äthiopien",
    "AU": "Australien",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesch",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgien",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivien",
    "BQ": "Bonaire",
    "BA": "Bosnien und Herzegowina",
    "BW": "Botswana",
    "BV": "Bouvetinsel",
    "BR": "Brasilien",
    "VG": "Britische Jungferninseln",
    "IO": "Britisches Territorium im Indischen Ozean",
    "BN": "Brunei Darussalam",
    "BG": "Bulgarien",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "CL": "Chile",
    "CN": "China",
    "CK": "Cookinseln",
    "CR": "Costa Rica",
    "CI": "Elfenbeinküste",
    "CW": "Curaçao",
    "DK": "Dänemark",
    "DE": "Deutschland",
    "DM": "Dominica",
    "DO": "Dominikanische Republik",
    "DJ": "Dschibuti",
    "EC": "Ecuador",
    "SV": "El Salvador",
    "ER": "Eritrea",
    "EE": "Estland",
    "FK": "Falklandinseln",
    "FO": "Färöer",
    "FJ": "Fidschi",
    "FI": "Finnland",
    "FR": "Frankreich",
    "GF": "Französisch-Guayana",
    "PF": "Französisch-Polynesien",
    "TF": "Französische Süd- und Antarktisgebiete",
    "GA": "Gabun",
    "GM": "Gambia",
    "GE": "Georgien",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GD": "Grenada",
    "GR": "Griechenland",
    "GL": "Grönland",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard und McDonaldinseln",
    "HN": "Honduras",
    "HK": "Hongkong",
    "IN": "Indien",
    "ID": "Indonesien",
    "IM": "Insel Man",
    "IQ": "Irak",
    "IR": "Iran",
    "IE": "Irland",
    "IS": "Island",
    "IL": "Israel",
    "IT": "Italien",
    "JM": "Jamaika",
    "JP": "Japan",
    "YE": "Jemen",
    "JE": "Jersey",
    "JO": "Jordanien",
    "KY": "Kaimaninseln",
    "KH": "Kambodscha",
    "CM": "Kamerun",
    "CA": "Kanada",
    "CV": "Kap Verde",
    "KZ": "Kasachstan",
    "QA": "Katar",
    "KE": "Kenia",
    "KG": "Kirgisistan",
    "KI": "Kiribati",
    "CC": "Kokosinseln",
    "CO": "Kolumbien",
    "KM": "Komoren",
    "CD": "Kongo",
    "KP": "Nordkorea",
    "KR": "Südkorea",
    "HR": "Kroatien",
    "CU": "Kuba",
    "KW": "Kuwait",
    "LA": "Laos",
    "LS": "Lesotho",
    "LV": "Lettland",
    "LB": "Libanon",
    "LR": "Liberia",
    "LY": "Libyen",
    "LI": "Liechtenstein",
    "LT": "Litauen",
    "LU": "Luxemburg",
    "MO": "Macao",
    "MG": "Madagaskar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Malediven",
    "ML": "Mali",
    "MT": "Malta",
    "MA": "Marokko",
    "MH": "Marshallinseln",
    "MQ": "Martinique",
    "MR": "Mauretanien",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexiko",
    "FM": "Mikronesien",
    "MD": "Moldawien",
    "MC": "Monaco",
    "MN": "Mongolei",
    "ME": "Montenegro",
    "MS": "Montserrat",
    "MZ": "Mosambik",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NC": "Neukaledonien",
    "NZ": "Neuseeland",
    "NI": "Nicaragua",
    "NL": "Niederlande",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "MK": "Nordmazedonien",
    "MP": "Nördliche Marianen",
    "NF": "Norfolkinsel",
    "NO": "Norwegen",
    "OM": "Oman",
    "AT": "Österreich",
    "TL": "Osttimor",
    "PK": "Pakistan",
    "PS": "Staat Palästina",
    "PW": "Palau",
    "PA": "Panama",
    "PG": "Papua-Neuguinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippinen",
    "PN": "Pitcairninseln",
    "PL": "Polen",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "TW": "Taiwan",
    "CG": "Republik Kongo",
    "RE": "Réunion",
    "RW": "Ruanda",
    "RO": "Rumänien",
    "RU": "Russische Föderation",
    "BL": "Saint-Barthélemy",
    "MF": "Saint-Martin",
    "SB": "Salomonen",
    "ZM": "Sambia",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "São Tomé und Príncipe",
    "SA": "Saudi-Arabien",
    "SE": "Schweden",
    "CH": "Schweiz",
    "SN": "Senegal",
    "RS": "Serbien",
    "SC": "Seychellen",
    "SL": "Sierra Leone",
    "ZW": "Simbabwe",
    "SG": "Singapur",
    "SX": "Sint Maarten",
    "SK": "Slowakei",
    "SI": "Slowenien",
    "SO": "Somalia",
    "ES": "Spanien",
    "LK": "Sri Lanka",
    "SH": "St. Helena",
    "KN": "St. Kitts und Nevis",
    "LC": "St. Lucia",
    "PM": "Saint-Pierre und Miquelon",
    "VC": "St. Vincent und die Grenadinen",
    "ZA": "Südafrika",
    "SD": "Sudan",
    "GS": "Südgeorgien und die Südlichen Sandwichinseln",
    "SS": "Südsudan",
    "SR": "Suriname",
    "SJ": "Svalbard und Jan Mayen",
    "SZ": "Eswatini",
    "SY": "Syrien, Arabische Republik",
    "TJ": "Tadschikistan",
    "TZ": "Tansania, Vereinigte Republik",
    "TH": "Thailand",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad und Tobago",
    "TD": "Tschad",
    "CZ": "Tschechische Republik",
    "TN": "Tunesien",
    "TR": "Türkei",
    "TM": "Turkmenistan",
    "TC": "Turks- und Caicosinseln",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "HU": "Ungarn",
    "UM": "United States Minor Outlying Islands",
    "UY": "Uruguay",
    "UZ": "Usbekistan",
    "VU": "Vanuatu",
    "VA": "Vatikanstadt",
    "VE": "Venezuela",
    "AE": "Vereinigte Arabische Emirate",
    "US": ["Vereinigte Staaten von Amerika", "Vereinigte Staaten", "USA"],
    "GB": ["Vereinigtes Königreich", "Großbritannien"],
    "VN": "Vietnam",
    "WF": "Wallis und Futuna",
    "CX": "Weihnachtsinsel",
    "EH": "Westsahara",
    "CF": "Zentralafrikanische Republik",
    "CY": "Zypern",
    "XK": "Kosovo"
};
CONST.COUNTRIES_TO_COUNTRY_CODE = {
    "Afghanistan": "AF",
    "Ägypten": "EG",
    "Åland": "AX",
    "Albanien": "AL",
    "Algerien": "DZ",
    "Amerikanisch-Samoa": "AS",
    "Amerikanische Jungferninseln": "VI",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarktis": "AQ",
    "Antigua und Barbuda": "AG",
    "Äquatorialguinea": "GQ",
    "Argentinien": "AR",
    "Armenien": "AM",
    "Aruba": "AW",
    "Aserbaidschan": "AZ",
    "Äthiopien": "ET",
    "Australien": "AU",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesch": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgien": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermuda": "BM",
    "Bhutan": "BT",
    "Bolivien": "BO",
    "Bonaire": "BQ",
    "Bosnien und Herzegowina": "BA",
    "Botswana": "BW",
    "Bouvetinsel": "BV",
    "Brasilien": "BR",
    "Britische Jungferninseln": "VG",
    "Britisches Territorium im Indischen Ozean": "IO",
    "Brunei Darussalam": "BN",
    "Bulgarien": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Chile": "CL",
    "China": "CN",
    "Cookinseln": "CK",
    "Costa Rica": "CR",
    "Elfenbeinküste": "CI",
    "Curaçao": "CW",
    "Dänemark": "DK",
    "Deutschland": "DE",
    "Dominica": "DM",
    "Dominikanische Republik": "DO",
    "Dschibuti": "DJ",
    "Ecuador": "EC",
    "El Salvador": "SV",
    "Eritrea": "ER",
    "Estland": "EE",
    "Falklandinseln": "FK",
    "Färöer": "FO",
    "Fidschi": "FJ",
    "Finnland": "FI",
    "Frankreich": "FR",
    "Französisch-Guayana": "GF",
    "Französisch-Polynesien": "PF",
    "Französische Süd- und Antarktisgebiete": "TF",
    "Gabun": "GA",
    "Gambia": "GM",
    "Georgien": "GE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Grenada": "GD",
    "Griechenland": "GR",
    "Grönland": "GL",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guernsey": "GG",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Heard und McDonaldinseln": "HM",
    "Honduras": "HN",
    "Hongkong": "HK",
    "Indien": "IN",
    "Indonesien": "ID",
    "Insel Man": "IM",
    "Irak": "IQ",
    "Iran": "IR",
    "Irland": "IE",
    "Island": "IS",
    "Israel": "IL",
    "Italien": "IT",
    "Jamaika": "JM",
    "Japan": "JP",
    "Jemen": "YE",
    "Jersey": "JE",
    "Jordanien": "JO",
    "Kaimaninseln": "KY",
    "Kambodscha": "KH",
    "Kamerun": "CM",
    "Kanada": "CA",
    "Kap Verde": "CV",
    "Kasachstan": "KZ",
    "Katar": "QA",
    "Kenia": "KE",
    "Kirgisistan": "KG",
    "Kiribati": "KI",
    "Kokosinseln": "CC",
    "Kolumbien": "CO",
    "Komoren": "KM",
    "Kongo": "CD",
    "Nordkorea": "KP",
    "Südkorea": "KR",
    "Kroatien": "HR",
    "Kuba": "CU",
    "Kuwait": "KW",
    "Laos": "LA",
    "Lesotho": "LS",
    "Lettland": "LV",
    "Libanon": "LB",
    "Liberia": "LR",
    "Libyen": "LY",
    "Liechtenstein": "LI",
    "Litauen": "LT",
    "Luxemburg": "LU",
    "Macao": "MO",
    "Madagaskar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Malediven": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marokko": "MA",
    "Marshallinseln": "MH",
    "Martinique": "MQ",
    "Mauretanien": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Mexiko": "MX",
    "Mikronesien": "FM",
    "Moldawien": "MD",
    "Monaco": "MC",
    "Mongolei": "MN",
    "Montenegro": "ME",
    "Montserrat": "MS",
    "Mosambik": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Neukaledonien": "NC",
    "Neuseeland": "NZ",
    "Nicaragua": "NI",
    "Niederlande": "NL",
    "Niger": "NE",
    "Nigeria": "NG",
    "Niue": "NU",
    "Nordmazedonien": "MK",
    "Nördliche Marianen": "MP",
    "Norfolkinsel": "NF",
    "Norwegen": "NO",
    "Oman": "OM",
    "Österreich": "AT",
    "Osttimor": "TL",
    "Pakistan": "PK",
    "Staat Palästina": "PS",
    "Palau": "PW",
    "Panama": "PA",
    "Papua-Neuguinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippinen": "PH",
    "Pitcairninseln": "PN",
    "Polen": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Taiwan": "TW",
    "Republik Kongo": "CG",
    "Réunion": "RE",
    "Ruanda": "RW",
    "Rumänien": "RO",
    "Russische Föderation": "RU",
    "Saint-Barthélemy": "BL",
    "Saint-Martin": "MF",
    "Salomonen": "SB",
    "Sambia": "ZM",
    "Samoa": "WS",
    "San Marino": "SM",
    "São Tomé und Príncipe": "ST",
    "Saudi-Arabien": "SA",
    "Schweden": "SE",
    "Schweiz": "CH",
    "Senegal": "SN",
    "Serbien": "RS",
    "Seychellen": "SC",
    "Sierra Leone": "SL",
    "Simbabwe": "ZW",
    "Singapur": "SG",
    "Sint Maarten": "SX",
    "Slowakei": "SK",
    "Slowenien": "SI",
    "Somalia": "SO",
    "Spanien": "ES",
    "Sri Lanka": "LK",
    "St. Helena": "SH",
    "St. Kitts und Nevis": "KN",
    "St. Lucia": "LC",
    "Saint-Pierre und Miquelon": "PM",
    "St. Vincent und die Grenadinen": "VC",
    "Südafrika": "ZA",
    "Sudan": "SD",
    "Südgeorgien und die Südlichen Sandwichinseln": "GS",
    "Südsudan": "SS",
    "Suriname": "SR",
    "Svalbard und Jan Mayen": "SJ",
    "Eswatini": "SZ",
    "Syrien, Arabische Republik": "SY",
    "Tadschikistan": "TJ",
    "Tansania, Vereinigte Republik": "TZ",
    "Thailand": "TH",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad und Tobago": "TT",
    "Tschad": "TD",
    "Tschechische Republik": "CZ",
    "Tunesien": "TN",
    "Türkei": "TR",
    "Turkmenistan": "TM",
    "Turks- und Caicosinseln": "TC",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "Ungarn": "HU",
    "United States Minor Outlying Islands": "UM",
    "Uruguay": "UY",
    "Usbekistan": "UZ",
    "Vanuatu": "VU",
    "Vatikanstadt": "VA",
    "Venezuela": "VE",
    "Vereinigte Arabische Emirate": "AE",
    "Vereinigte Staaten von Amerika,Vereinigte Staaten,USA": "US",
    "Vereinigtes Königreich,Großbritannien": "GB",
    "Vietnam": "VN",
    "Wallis und Futuna": "WF",
    "Weihnachtsinsel": "CX",
    "Westsahara": "EH",
    "Zentralafrikanische Republik": "CF",
    "Zypern": "CY",
    "Kosovo": "XK"
};

export default CONST;
